apiVersion: v1
kind: ConfigMap
metadata:
  name: scenario-2-cm
data:
  db-app.conf: |-
    {{ .Files.Get "db-app.conf" | indent 4 }}
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: scenario-3-cm
data:
  db-app.conf: |-
    ## This is dummy configuration file ##
      conf {
        user: ADMIN
        pwd: PASSWORD
        dir: /home
        }
---

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-1
spec:
  containers:
  ## Main Container
  - image: nginx
    name: application
    volumeMounts:
    - name: db-conf
      mountPath: /etc/db-app.conf # This should be your final destination
      subPath: db-app.conf  # The name of the file to be placed inside /etc, the filename used here and in mountPath should be same.

  ## Sidecar Container
  - name: sidecar
    image: busybox
    args:
     - /bin/sh
     - -c
     - sleep 36000
    volumeMounts:
    - name: db-conf
      mountPath: /etc/db-app.conf # This should be your final destination
      subPath: db-app.conf # The name of the file to be placed inside /etc, the filename used here and in mountPath should be same.
  # Define the volumes to be used by these containers
  volumes:
  - name: db-conf # To access this volume, this name must be used inside volumeMounts of the container
    configMap:
       name: scenario-2-cm # Name of the configMap
       items:
         - key: db-app.conf  # Name of the item we had used inside our ConfigMap (under data:)
           path: db-app.conf # Name of the file to be placed inside /etc
